OnlineShoppingSystem/OnlineShoppingSystem/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingSystem.Dao;
using OnlineShoppingSystem.Models;
using OnlineShoppingSystem.Service;

namespace OnlineShoppingSystem.Controllers
{
    public class CartController : Controller
    {
        private ShoppingCartService shoppingCartService = new ShoppingCartService();
        private const string CartSession = "CartSession";

        // GET: Cart
        public ActionResult ShowCart()
        {
            var cart = Session[CartSession];
            var listCart = (List<ShoppingCartDto>) cart;

            return View(listCart);
        }

        // Add products to Cart
        public ActionResult AddToCart(long productId, int quantity)
        {
            var account = (User) Session["Account"];
            if (account == null)
            {
                return RedirectToAction("Login", "Login");
            }
            var cart = Session[CartSession];
            Session[CartSession] = shoppingCartService.AddToCart(productId, quantity, account, cart);
            return RedirectToAction("ShowCart");
        }

        //Remove all items
        public ActionResult RemoveAllItems()
        {
            Session.Remove(CartSession);
            return RedirectToAction("ShowCart");
        }

        //Remove one item
        public ActionResult RemoveSpecificItem(long id)
        {
            var listCart = (List<ShoppingCartDto>) Session[CartSession];
            listCart.RemoveAll(x => x.ProductId == id);
            Session[CartSession] = listCart;

            return RedirectToAction("ShowCart");
        }
    }
}

OnlineShoppingSystem/OnlineShoppingSystem/Controllers/CheckOutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingSystem.Models;
using OnlineShoppingSystem.Service;

namespace OnlineShoppingSystem.Controllers
{
    public class CheckOutController : Controller
    {
        private OrderService orderService = new OrderService();
        private const string CartSession = "CartSession";

        //Show CheckOut
        public ActionResult ShowCheckOut()
        {
            var cart = Session[CartSession];
            var listCart = (List<ShoppingCartDto>) cart;

            return View(listCart);
        }

        //Save order into database
        public ActionResult CheckOut()
        {
            var cart = Session[CartSession];
            var listCart = (List<ShoppingCartDto>) cart;
            orderService.AddOrder(listCart);
            Session.Remove(CartSession);
            Session.Remove("NumberOfProductInCart");

            return RedirectToAction("GetMessagePlaceOrder");
        }

        //Show message for successful order
        public ActionResult GetMessagePlaceOrder()
        {
            return View();
        }

        //Show order for customer
        public ActionResult ShowOrder()
        {
            var account = (User) Session["Account"];
            return View(orderService.GetOrder(account));
        }

        //Show detail order
        public ActionResult ShowOrderDetail(long orderId)
        {
            return View(orderService.GetOrderDetails(orderId));
        }
    }
}

OnlineShoppingSystem/OnlineShoppingSystem/Controllers/ProductDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingSystem.Service;

namespace OnlineShoppingSystem.Controllers
{
    public class ProductDetailsController : Controller
    {
        private ShoppingService shoppingService = new ShoppingService();

        public ActionResult ShowDetailProduct(long id)
        {
            Session["RelatedProduct"] = shoppingService.GetRandomProductByCategory(id);
            return View(shoppingService.GetDetailProduct(id));
        }
    }
}

OnlineShoppingSystem/OnlineShoppingSystem/Controllers/SearchProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingSystem.Service;

namespace OnlineShoppingSystem.Controllers
{
    public class SearchProductController : Controller
    {
        private ShoppingService shoppingService = new ShoppingService();

        //GET : SearchProduct
        public ActionResult Search()
        {
            return View();
        }

        // POST: SearchProduct
        [HttpPost]
        public ActionResult Search(string searchKey)
        {
            ViewBag.SearchKey = shoppingService.SearchProduct(searchKey);
            return View();
        }
    }
}

OnlineShoppingSystem/OnlineShoppingSystem/Views/CheckOut/GetMessagePlaceOrder.cshtml
@using System.Web.Mvc.Html
@using OnlineShoppingSystem.Models
@model IEnumerable<OnlineShoppingSystem.Models.ShoppingCartDto>

@{
    ViewBag.Title = "GetMessagePlaceOrder";
    Layout = "~/Views/Shared/_ShoppingLayout.cshtml";
}

<link rel="stylesheet" type="text/css" href="../../Content/ShoppingUI/styles/checkout.css">
<link rel="stylesheet" type="text/css" href="../../Content/ShoppingUI/styles/checkout_responsive.css">
<script src="../../Content/ShoppingUI/js/checkout.js"></script>

<div class="super_container">
    <header class="header">
        <div class="header_container">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="header_content d-flex flex-row align-items-center justify-content-start">
                            <div class="logo">@Html.ActionLink("LAPTOP", "Home", "Home")</div>
                            <nav class="main_nav">
                                <ul>
                                    <li>@Html.ActionLink("Trang chủ", "Home", "Home")</li>
                                    <li class="hassubs">
                                        <a href="#">Loại mặt hàng</a>
                                        <ul>
                                            @{
                                                var listCategories = (List<Category>)Session["Category"];
                                                foreach (var item in listCategories)
                                                {
                                                    <li><a href=@Url.Action("ShowCategory","Category", new { id = item.CategoryID })>@item.CategoryName</a></li>
                                                }
                                            }
                                        </ul>
                                    </li>
                                    <li><a href="#">Hàng đang sale</a></li>
                                    <li><a href="#">Liên hệ</a></li>
                                </ul>
                            </nav>
                            <div class="header_extra ml-auto">
                                @{
                                    var data = (string)Session["Name"];
                                }
                                @if (data == null)
                                {
                                    @Html.ActionLink("Đăng nhập", "Login", "Login")
                                    <span>&nbsp;|&nbsp;</span>
                                }
                                else
                                {
                                    <div>Xin chào <a href="@Url.Action("DetailAccount", "Account")">@data</a> | @Html.ActionLink("Đăng xuất", "Logout", "Login")</div>
                                }
                                <div class="shopping_cart">
                                    <a href=@Url.Action("ShowCart", "Cart")>
                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                             viewBox="0 0 489 489" style="enable-background: new 0 0 489 489;" xml:space="preserve">
                                        <g>
                                        <path d="M440.1,422.7l-28-315.3c-0.6-7-6.5-12.3-13.4-12.3h-57.6C340.3,42.5,297.3,0,244.5,0s-95.8,42.5-96.6,95.1H90.3
													c-7,0-12.8,5.3-13.4,12.3l-28,315.3c0,0.4-0.1,0.8-0.1,1.2c0,35.9,32.9,65.1,73.4,65.1h244.6c40.5,0,73.4-29.2,73.4-65.1
													C440.2,423.5,440.2,423.1,440.1,422.7z M244.5,27c37.9,0,68.8,30.4,69.6,68.1H174.9C175.7,57.4,206.6,27,244.5,27z M366.8,462
													H122.2c-25.4,0-46-16.8-46.4-37.5l26.8-302.3h45.2v41c0,7.5,6,13.5,13.5,13.5s13.5-6,13.5-13.5v-41h139.3v41
													c0,7.5,6,13.5,13.5,13.5s13.5-6,13.5-13.5v-41h45.2l26.9,302.3C412.8,445.2,392.1,462,366.8,462z" />
                                            </g>
                                        </svg>
                                        <div>Giỏ hàng</div>
                                    </a>
                                </div>
                                <div class="search">
                                    <div class="search_icon">
                                        <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                             viewBox="0 0 475.084 475.084" style="enable-background: new 0 0 475.084 475.084;"
                                             xml:space="preserve">
                                        <g>
                                        <path d="M464.524,412.846l-97.929-97.925c23.6-34.068,35.406-72.047,35.406-113.917c0-27.218-5.284-53.249-15.852-78.087
												c-10.561-24.842-24.838-46.254-42.825-64.241c-17.987-17.987-39.396-32.264-64.233-42.826
												C254.246,5.285,228.217,0.003,200.999,0.003c-27.216,0-53.247,5.282-78.085,15.847C98.072,26.412,76.66,40.689,58.673,58.676
												c-17.989,17.987-32.264,39.403-42.827,64.241C5.282,147.758,0,173.786,0,201.004c0,27.216,5.282,53.238,15.846,78.083
												c10.562,24.838,24.838,46.247,42.827,64.234c17.987,17.993,39.403,32.264,64.241,42.832c24.841,10.563,50.869,15.844,78.085,15.844
												c41.879,0,79.852-11.807,113.922-35.405l97.929,97.641c6.852,7.231,15.406,10.849,25.693,10.849
												c9.897,0,18.467-3.617,25.694-10.849c7.23-7.23,10.848-15.796,10.848-25.693C475.088,428.458,471.567,419.889,464.524,412.846z
												 M291.363,291.358c-25.029,25.033-55.148,37.549-90.364,37.549c-35.21,0-65.329-12.519-90.36-37.549
												c-25.031-25.029-37.546-55.144-37.546-90.36c0-35.21,12.518-65.334,37.546-90.36c25.026-25.032,55.15-37.546,90.36-37.546
												c35.212,0,65.331,12.519,90.364,37.546c25.033,25.026,37.548,55.15,37.548,90.36C328.911,236.214,316.392,266.329,291.363,291.358z
												" />
                                            </g>
                                        </svg>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Search Panel -->
        <div class="search_panel trans_300">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="search_panel_content d-flex flex-row align-items-center justify-content-end">
                            @using (Html.BeginForm("Search", "SearchProduct", FormMethod.Post))
                            {
                                <input type="text" name="searchKey" class="search_input" placeholder="Nhập tên sản phẩm hoặc hãng..." required="required">
                                <input type="submit" class="btn btn-info" value="Tìm kiếm" />
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Social -->
        <div class="header_social">
            <ul>
                <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
            </ul>
        </div>
    </header>

    <!-- Home -->

    <div class="home">
        <div class="home_container">
            <div class="home_background" style="background-image:url(../../Content/ShoppingUI/images/searchproductheader.jpg)"></div>
            <div class="home_content_container">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="home_content">
                                <div class="breadcrumbs">
                                    <ul>
                                        <li>@Html.ActionLink("Trang chủ", "Home", "Home")</li>
                                        <li>@Html.ActionLink("Giỏ hàng", "ShowCart", "Cart")</li>
                                        <li>Thanh toán</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Message -->
    <br/><br/>
    <div style="text-align: center; font-size: 180%; color: green">
        Đặt hàng thành công, bạn có thể tiếp tục tạo đơn hàng mới hoặc xem đơn hàng đã đặt!
    </div>
    <br/>
    <div style="text-align: center">
        <a href="@Url.Action("Home", "Home")" class="btn btn-info" role="button">Về trang chủ</a>
        <a href="@Url.Action("ShowOrder", "CheckOut")" class="btn btn-success" role="button">Xem đơn hàng đã đặt</a>
    </div>
</div>

OnlineShoppingSystem/OnlineShoppingSystem/Views/CheckOut/ShowOrderDetail.cshtml
@using OnlineShoppingSystem.Models
@model IEnumerable<OnlineShoppingSystem.Models.ShoppingCartDto>


@{
    ViewBag.Title = "ShowOrderDetail";
    Layout = "~/Views/Shared/_ShoppingLayout.cshtml";
}

<link rel="stylesheet" type="text/css" href="../../Content/ShoppingUI/styles/cart.css">
<link rel="stylesheet" type="text/css" href="../../Content/ShoppingUI/styles/cart_responsive.css">
<script src="../../Content/ShoppingUI/js/cart.js"></script>

<div class="super_container">

    <!-- Header -->

    <header class="header">
        <div class="header_container">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="header_content d-flex flex-row align-items-center justify-content-start">
                            <div class="logo">@Html.ActionLink("LAPTOP", "Home", "Home")</div>
                            <nav class="main_nav">
                                <ul>
                                    <li>@Html.ActionLink("Trang chủ", "Home", "Home")</li>
                                    <li class="hassubs">
                                        <a href="#">Loại mặt hàng</a>
                                        <ul>
                                            @{
                                                var listCategories = (List<Category>)Session["Category"];
                                                foreach (var item in listCategories)
                                                {
                                                    <li><a href=@Url.Action("ShowCategory", "Category", new {id = item.CategoryID})>@item.CategoryName</a></li>
                                                }
                                            }
                                        </ul>
                                    </li>
                                    <li><a href="#">Hàng đang sale</a></li>
                                    <li><a href="#">Liên hệ</a></li>
                                </ul>
                            </nav>
                            <div class="header_extra ml-auto">
                                @{
                                    var data = (string)Session["Name"];
                                }
                                @if (data == null)
                                {
                                    @Html.ActionLink("Đăng nhập", "Login", "Login")
                                    <span>&nbsp;|&nbsp;</span>
                                }
                                else
                                {
                                    <div>Xin chào <a href="@Url.Action("DetailAccount", "Account")">@data</a> | @Html.ActionLink("Đăng xuất", "Logout", "Login")</div>
                                }
                                <div class="shopping_cart">
                                    <a href=@Url.Action("ShowCart", "Cart")>
                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                             viewBox="0 0 489 489" style="enable-background: new 0 0 489 489;" xml:space="preserve">
                                        <g>
                                        <path d="M440.1,422.7l-28-315.3c-0.6-7-6.5-12.3-13.4-12.3h-57.6C340.3,42.5,297.3,0,244.5,0s-95.8,42.5-96.6,95.1H90.3
													c-7,0-12.8,5.3-13.4,12.3l-28,315.3c0,0.4-0.1,0.8-0.1,1.2c0,35.9,32.9,65.1,73.4,65.1h244.6c40.5,0,73.4-29.2,73.4-65.1
													C440.2,423.5,440.2,423.1,440.1,422.7z M244.5,27c37.9,0,68.8,30.4,69.6,68.1H174.9C175.7,57.4,206.6,27,244.5,27z M366.8,462
													H122.2c-25.4,0-46-16.8-46.4-37.5l26.8-302.3h45.2v41c0,7.5,6,13.5,13.5,13.5s13.5-6,13.5-13.5v-41h139.3v41
													c0,7.5,6,13.5,13.5,13.5s13.5-6,13.5-13.5v-41h45.2l26.9,302.3C412.8,445.2,392.1,462,366.8,462z" />
                                            </g>
                                        </svg>
                                        @{
                                            var numberProduct = 0;
                                            if (Session["NumberOfProductInCart"] != null)
                                            {
                                                numberProduct = (int) Session["NumberOfProductInCart"];
                                            }
                                        }
                                        <div>Giỏ hàng @if(numberProduct != 0) { <span>(@numberProduct)</span> }</div>
                                    </a>
                                </div>
                                <div class="search">
                                    <div class="search_icon">
                                        <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                             viewBox="0 0 475.084 475.084" style="enable-background: new 0 0 475.084 475.084;"
                                             xml:space="preserve">
                                        <g>
                                        <path d="M464.524,412.846l-97.929-97.925c23.6-34.068,35.406-72.047,35.406-113.917c0-27.218-5.284-53.249-15.852-78.087
												c-10.561-24.842-24.838-46.254-42.825-64.241c-17.987-17.987-39.396-32.264-64.233-42.826
												C254.246,5.285,228.217,0.003,200.999,0.003c-27.216,0-53.247,5.282-78.085,15.847C98.072,26.412,76.66,40.689,58.673,58.676
												c-17.989,17.987-32.264,39.403-42.827,64.241C5.282,147.758,0,173.786,0,201.004c0,27.216,5.282,53.238,15.846,78.083
												c10.562,24.838,24.838,46.247,42.827,64.234c17.987,17.993,39.403,32.264,64.241,42.832c24.841,10.563,50.869,15.844,78.085,15.844
												c41.879,0,79.852-11.807,113.922-35.405l97.929,97.641c6.852,7.231,15.406,10.849,25.693,10.849
												c9.897,0,18.467-3.617,25.694-10.849c7.23-7.23,10.848-15.796,10.848-25.693C475.088,428.458,471.567,419.889,464.524,412.846z
												 M291.363,291.358c-25.029,25.033-55.148,37.549-90.364,37.549c-35.21,0-65.329-12.519-90.36-37.549
												c-25.031-25.029-37.546-55.144-37.546-90.36c0-35.21,12.518-65.334,37.546-90.36c25.026-25.032,55.15-37.546,90.36-37.546
												c35.212,0,65.331,12.519,90.364,37.546c25.033,25.026,37.548,55.15,37.548,90.36C328.911,236.214,316.392,266.329,291.363,291.358z
												" />
                                            </g>
                                        </svg>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Search Panel -->
        <div class="search_panel trans_300">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="search_panel_content d-flex flex-row align-items-center justify-content-end">
                            @using (Html.BeginForm("Search", "SearchProduct", FormMethod.Post))
                            {
                                <input type="text" name="searchKey" class="search_input" placeholder="Nhập tên sản phẩm hoặc hãng..." required="required">
                                <input type="submit" class="btn btn-info" value="Tìm kiếm" />
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Social -->
        <div class="header_social">
            <ul>
                <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
            </ul>
        </div>
    </header>

    <!-- Show Order -->

    <div class="home">
        <div class="home_container">
            <div class="home_background" style="background-image:url(../../Content/ShoppingUI/images/searchproductheader.jpg)"></div>
            <div class="home_content_container">
                <div class="container">
                    <div class="row">
                        <div class="col">
                            <div class="home_content">
                                <div class="breadcrumbs">
                                    <ul>
                                        <li>@Html.ActionLink("Trang chủ", "Home", "Home")</li>
                                        <li>@Html.ActionLink("Đơn hàng của bạn", "ShowOrder", "CheckOut")</li>
                                        <li>Chi tiết đơn hàng</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <br /><br />

    <div class="row">
        <div class="col">
            <!-- Column Titles -->
            <div class="cart_info_columns clearfix">
                <div class="cart_info_col cart_info_col_product" style="left: 200px">Sản phẩm</div>
                <div class="cart_info_col cart_info_col_price">Đơn giá</div>
                <div class="cart_info_col cart_info_col_quantity">Số lượng</div>
                <div class="cart_info_col cart_info_col_total">Thành tiền</div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row cart_items_row">
            <div class="col">
                <!-- Cart Item -->
                @foreach (var item in Model)
                {
                    <div class="cart_item d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start">
                        <!-- Name -->
                        <div class="cart_item_product d-flex flex-row align-items-center justify-content-start">
                            <div class="cart_item_image">
                                <div><img src="@Url.Content("~/Content/ShoppingUI/images/" + item.Image)" alt=""></div>
                            </div>
                            <div class="cart_item_name_container">
                                <div class="cart_item_name"><a href=@Url.Action("ShowDetailProduct", "ProductDetails", new {id = item.ProductId})>@item.ProductName</a></div>
                            </div>
                        </div>
                        <!-- Price -->
                        <div class="cart_item_price">@string.Format("{0:0,0}", item.Price) đ</div>
                        <!-- Quantity -->
                        <div class="cart_item_quantity">
                            <div class="product_quantity_container">
                                <b>@item.Quantity</b>
                            </div>
                        </div>
                        <!-- Total -->
                        <div class="cart_item_total">@string.Format("{0:0,0}", item.TotalPrice) đ</div>
                    </div>
                }
                @{
                    decimal total = 0;
                    foreach (var item in Model)
                    {
                        total += item.TotalPrice;
                    }
                }
                <div style="font-size: 25px; text-align: center; color: black">Tổng tiền hàng: @string.Format("{0:0,0}", total) đ</div>
                <br/>
                <div style="text-align: center">
                    <a href="@Url.Action("ShowOrder", "CheckOut")" class="btn btn-primary" role="button">Về đơn hàng</a>
                </div>
                <br/>
            </div>
        </div>
    </div>
</div>